#! /bin/sh

# Autostart script
$HOME/.config/bspwm/autostart.sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor DVI-I-0 -d 1
bspc monitor HDMI-0 -d 2 3 4 5 6 7 8

# Visual Settings
bspc config border_width            2
bspc config window_gap              10
bspc config top_padding 		    0

bspc config focused_border_color    "#F9D976"
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_motion_interval 40
bspc config ignore_ewmh_focus       true

# Window Rules
bspc rule -a Discord desktop='^1' follow=on
bspc rule -a Caprine desktop='^2' follow=on
bspc rule -a subl desktop='^4' follow=on
bspc rule -a Lutris desktop='^5' follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a timeshift-gtk state=floating follow=on
bspc rule -a spotify desktop='^6' follow=on
bspc rule -a Steam desktop='^5' follow=on

#fix for moving spotify to specific workspace
bspc config external_rules_command $HOME/.config/bspwm/scripts/external_rules_command

# Game Window Rules
bspc rule -a isaac-ng.exe state=pseudo_tiled center=true
bspc rule -a steam_app_250900 state=pseudo_tiled center=true #Binding of Isaac

bspc rule -a leagueclientux.exe state=pseudo_tiled center=true

### External rules from Arcolinux config ###
## Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
## Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window